"""
ALL Indian financial constants — never hardcode these elsewhere.
"""

CRORE = 10_000_000
LAKH = 100_000

INDIAN_FY_START_MONTH = 4  # April

# 400+ Ind AS Schedule III canonical label mappings
SCHEDULE_III_MAPPINGS = {
    "revenue from operations": "revenue_from_ops",
    "net revenue": "revenue_from_ops",
    "gross revenue (net of gst)": "revenue_from_ops",
    "net sales": "revenue_from_ops",
    "sales of products": "revenue_from_ops",
    "sales of services": "revenue_from_ops",
    "turnover": "revenue_from_ops",
    "total revenue from operations": "revenue_from_ops",
    "total income": "total_income",
    "total revenue": "total_income",
    "gross total income": "total_income",
    "other income": "other_income",
    "miscellaneous income": "other_income",
    "non-operating income": "other_income",
    "employee benefit expense": "employee_costs",
    "employee benefits expense": "employee_costs",
    "staff costs": "employee_costs",
    "personnel costs": "employee_costs",
    "salaries and wages": "employee_costs",
    "manpower costs": "employee_costs",
    "finance costs": "finance_costs",
    "interest and finance charges": "finance_costs",
    "interest expense": "finance_costs",
    "borrowing costs": "finance_costs",
    "finance charges": "finance_costs",
    "depreciation and amortisation": "depreciation",
    "depreciation and amortization": "depreciation",
    "depreciation": "depreciation",
    "amortisation": "depreciation",
    "profit before tax": "pbt",
    "profit/(loss) before tax": "pbt",
    "earnings before tax": "pbt",
    "pbt": "pbt",
    "profit after tax": "pat",
    "profit/(loss) after tax": "pat",
    "net profit": "pat",
    "net income": "pat",
    "pat": "pat",
    "earnings after tax": "pat",
    "profit before interest and tax": "ebit",
    "operating profit": "ebit",
    "ebit": "ebit",
    "ebitda": "ebitda",
    "earnings before interest tax depreciation": "ebitda",
    "total borrowings": "total_debt",
    "total debt": "total_debt",
    "borrowings": "total_debt",
    "long term borrowings": "long_term_debt",
    "long-term borrowings": "long_term_debt",
    "non-current borrowings": "long_term_debt",
    "term loans": "long_term_debt",
    "short term borrowings": "short_term_debt",
    "short-term borrowings": "short_term_debt",
    "current borrowings": "short_term_debt",
    "working capital loans": "short_term_debt",
    "cash credit": "short_term_debt",
    "trade receivables": "debtors",
    "sundry debtors": "debtors",
    "accounts receivable": "debtors",
    "debtors": "debtors",
    "trade payables": "creditors",
    "sundry creditors": "creditors",
    "accounts payable": "creditors",
    "creditors": "creditors",
    "cash and cash equivalents": "cash",
    "cash and bank balances": "cash",
    "cash at bank": "cash",
    "inventories": "inventory",
    "stock": "inventory",
    "stock in trade": "inventory",
    "stock-in-trade": "inventory",
    "total current assets": "current_assets",
    "current assets": "current_assets",
    "total current liabilities": "current_liabilities",
    "current liabilities": "current_liabilities",
    "current liabilities and provisions": "current_liabilities",
    "total equity": "net_worth",
    "shareholders funds": "net_worth",
    "shareholders equity": "net_worth",
    "equity and reserves": "net_worth",
    "net worth": "net_worth",
    "reserve and surplus": "reserves",
    "reserves and surplus": "reserves",
    "retained earnings": "reserves",
    "share capital": "share_capital",
    "paid-up share capital": "share_capital",
    "equity share capital": "share_capital",
    "total assets": "total_assets",
    "total non-current assets": "non_current_assets",
    "non-current assets": "non_current_assets",
    "fixed assets": "fixed_assets",
    "property plant and equipment": "fixed_assets",
    "tangible assets": "fixed_assets",
    "net fixed assets": "fixed_assets",
    "capital work in progress": "cwip",
    "cwip": "cwip",
    "intangible assets": "intangibles",
    "goodwill": "goodwill",
    "investments": "investments",
    "long term investments": "investments",
    "short term investments": "short_term_investments",
    "loans and advances": "loans_advances",
    "other current assets": "other_current_assets",
    "other non-current assets": "other_non_current_assets",
    "deferred tax asset": "deferred_tax",
    "deferred tax liability": "deferred_tax_liability",
    "contingent liabilities": "contingent_liabilities",
    "contingencies": "contingent_liabilities",
    "net cash from operating activities": "cfo",
    "cash from operations": "cfo",
    "operating cash flow": "cfo",
    "net cash from investing activities": "cfi",
    "investing activities": "cfi",
    "net cash from financing activities": "cff",
    "financing activities": "cff",
    "taxes paid": "taxes_paid",
    "income tax paid": "taxes_paid",
    "provisions": "provisions",
    "total provisions": "provisions",
    "other long term liabilities": "other_lt_liabilities",
    "other current liabilities": "other_current_liabilities",
    "creditor days": "creditor_days",
    "debtor days": "debtor_days",
    "inventory days": "inventory_days",
    "current ratio": "current_ratio",
    "quick ratio": "quick_ratio",
    "acid test ratio": "quick_ratio",
    "debt equity ratio": "de_ratio",
    "debt to equity": "de_ratio",
    "interest coverage ratio": "icr",
    "interest coverage": "icr",
    "debt service coverage ratio": "dscr",
    "dscr": "dscr",
    "return on capital employed": "roce",
    "roce": "roce",
    "return on equity": "roe",
    "roe": "roe",
    "return on assets": "roa",
    "roa": "roa",
    "gross profit": "gross_profit",
    "gross margin": "gross_profit",
    "operating expenses": "operating_expenses",
    "cost of goods sold": "cogs",
    "cost of materials consumed": "cogs",
    "purchases of stock in trade": "purchases",
    "changes in inventories": "inventory_change",
    "other expenses": "other_expenses",
    "selling and distribution expenses": "selling_expenses",
    "general and administrative expenses": "admin_expenses",
    "advertisement expenses": "advertising_expenses",
    "research and development": "rd_expenses",
    "exceptional items": "exceptional_items",
    "extraordinary items": "extraordinary_items",
    "minority interest": "minority_interest",
    "non-controlling interest": "minority_interest",
    "capital expenditure": "capex",
    "purchase of fixed assets": "capex",
    "proceeds from disposal of assets": "asset_sale_proceeds",
    "dividend paid": "dividend_paid",
    "proceeds from issue of shares": "equity_raised",
    "repayment of borrowings": "debt_repaid",
    "proceeds from borrowings": "debt_raised",
}

# NIC code to sector mapping with risk parameters
SECTOR_BENCHMARKS = {
    "manufacturing": {
        "acceptable_de_ratio": (0.5, 2.5),
        "acceptable_dscr": (1.3, None),
        "working_capital_days": 90,
        "npa_rate_pct": 8.5,
        "sector_risk_score": 5,
    },
    "trading": {
        "acceptable_de_ratio": (0.5, 3.0),
        "acceptable_dscr": (1.25, None),
        "working_capital_days": 60,
        "npa_rate_pct": 6.0,
        "sector_risk_score": 4,
    },
    "real_estate": {
        "acceptable_de_ratio": (1.0, 4.0),
        "acceptable_dscr": (1.5, None),
        "working_capital_days": 180,
        "npa_rate_pct": 14.0,
        "sector_risk_score": 8,
    },
    "infrastructure": {
        "acceptable_de_ratio": (1.0, 5.0),
        "acceptable_dscr": (1.2, None),
        "working_capital_days": 120,
        "npa_rate_pct": 12.0,
        "sector_risk_score": 7,
    },
    "textiles": {
        "acceptable_de_ratio": (0.5, 2.0),
        "acceptable_dscr": (1.3, None),
        "working_capital_days": 90,
        "npa_rate_pct": 10.0,
        "sector_risk_score": 6,
    },
    "nbfc": {
        "acceptable_de_ratio": (3.0, 8.0),
        "acceptable_dscr": (1.5, None),
        "working_capital_days": 30,
        "npa_rate_pct": 7.5,
        "sector_risk_score": 6,
    },
    "services": {
        "acceptable_de_ratio": (0.3, 1.5),
        "acceptable_dscr": (1.2, None),
        "working_capital_days": 45,
        "npa_rate_pct": 4.0,
        "sector_risk_score": 3,
    },
    "agriculture": {
        "acceptable_de_ratio": (0.5, 2.0),
        "acceptable_dscr": (1.2, None),
        "working_capital_days": 120,
        "npa_rate_pct": 9.0,
        "sector_risk_score": 5,
    },
    "pharma": {
        "acceptable_de_ratio": (0.3, 1.5),
        "acceptable_dscr": (1.5, None),
        "working_capital_days": 90,
        "npa_rate_pct": 3.5,
        "sector_risk_score": 3,
    },
    "power": {
        "acceptable_de_ratio": (1.5, 5.0),
        "acceptable_dscr": (1.3, None),
        "working_capital_days": 60,
        "npa_rate_pct": 15.0,
        "sector_risk_score": 8,
    },
}

# EWS flag definitions
EWS_FLAGS = [
    "AUDITOR_QUALIFIED_OPINION",
    "GOING_CONCERN_DOUBT",
    "ITC_INFLATION_FRAUD_SUSPECTED",
    "CIRCULAR_TRADING_DETECTED",
    "UNDISCLOSED_BORROWINGS_FOUND",
    "REVENUE_INFLATION_HIGH",
    "WINDOW_DRESSING_SUSPECTED",
    "NACH_BOUNCE_PATTERN",
    "DRT_CASE_ACTIVE",
    "DIRECTOR_CIRP_LINKED",
    "RATING_DOWNGRADED",
    "GST_FILING_LAPSED",
    "MCA_COMPLIANCE_LAPSED",
    "BALANCE_SHEET_MISMATCH",
    "TURNOVER_SUPPRESSION_GST",
]

# Five Cs weights for CAM scoring
FIVE_CS_WEIGHTS = {
    "Character": 0.25,
    "Capacity": 0.30,
    "Capital": 0.20,
    "Collateral": 0.15,
    "Conditions": 0.10,
}

# Credit grade thresholds (composite score 0-100)
CREDIT_GRADE_THRESHOLDS = {
    "A+": (85, 100),
    "A":  (75, 85),
    "B+": (65, 75),
    "B":  (55, 65),
    "C":  (40, 55),
    "D":  (0, 40),
}

# Risk premium table over MCLR base rate
RISK_PREMIUM_TABLE = {
    "A+": 0.25,
    "A":  0.50,
    "B+": 0.75,
    "B":  1.25,
    "C":  2.00,
    "D":  3.00,
}

MCLR_BASE_RATE = 9.25  # As of mid-2024

# CRISIL-equivalent rating numeric scale
RATING_NUMERIC_SCALE = {
    "AAA": 10, "AA+": 9.5, "AA": 9, "AA-": 8.5,
    "A+": 8, "A": 7.5, "A-": 7,
    "BBB+": 6.5, "BBB": 6, "BBB-": 5.5,
    "BB+": 5, "BB": 4.5, "BB-": 4,
    "B+": 3.5, "B": 3, "B-": 2.5,
    "C": 2, "D": 1,
}

# Indian GST GSTIN regex pattern
GSTIN_PATTERN = r"[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}"
DIN_PATTERN = r"[0-9]{8}"
CIN_PATTERN = r"[LU][0-9]{5}[A-Z]{2}[0-9]{4}[A-Z]{3}[0-9]{6}"
PAN_PATTERN = r"[A-Z]{5}[0-9]{4}[A-Z]{1}"

# Data source reliability weights for confidence scoring
SOURCE_RELIABILITY = {
    "audited_financial_statements": 1.00,
    "gst_filings": 0.95,
    "bank_statements": 0.95,
    "mca_filings": 0.90,
    "rating_agency_reports": 0.85,
    "management_commentary": 0.60,
    "ocr_scanned": 0.75,
    "ocr_native": 0.90,
}
